services:
  - type: web
    name: directus-self-host
    runtime: image
    autoDeploy: false
    image:
      url: directus/directus:11.0.2
    plan: free
    healthCheckPath: /server/health
    envVars:
      - key: KEY
        generateValue: true
      - key: SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: DB_CLIENT
        value: pg
      - key: DB_SSL__REJECT_UNAUTHORIZED
        value: "false"
